server:
  port: 8103
security:
  jwt:
    # 秘钥
    secretKey: idlelong
    # 过期时间 单位小时
    expiration:
      time: 12
spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://124.222.209.142:3206/rbac?characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: idlelong
    driver-class-name: com.mysql.jdbc.Driver
# MP 配置
mybatis-plus:
  mapper-locations: classpath*:/**/mapper/*Mapper.xml
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
      # 配置控制台打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # id生成规则,自增
      id-type: auto
logging:
  level:
    root: info