server:
  port: 8106
spring:
  application:
    name: oauth2-jwt-service
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: idlelong # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）